# Generated by Django 3.1.5 on 2021-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='song',
            name='song_playtime',
            field=models.DateField( verbose_name='song playtime'),
            preserve_default=False,
        ),
    ]
