# Generated by Django 3.1.5 on 2021-01-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210108_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_playtime',
            field=models.CharField(max_length=50),
        ),
    ]
