# Generated by Django 3.1.5 on 2021-01-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210108_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
